services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    App\Unit\BackupService:
        tags:
            - { name: uply.unit.service, identifier: backup }

    App\Unit\Backup\Scrutinizer:

    App\Repository\Unit\BackupRepository:
        public: true
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - App\Entity\Unit\Backup
