services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false
        bind:
            $googlePageSpeedApiKey: '%env(GOOGLE_PAGE_SPEED_KEY)%'

    App\Unit\GooglePageSpeedService:
        tags:
            - { name: uply.unit.service, identifier: google_page_speed }

    App\Unit\GooglePageSpeed\Scrutinizer:

    App\Repository\Unit\GooglePageSpeedRepository:
        public: true
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - App\Entity\Unit\GooglePageSpeed
