monolog:
    channels: ['scrutinizer', 'loop']
    handlers:
        scrutinizer:
            level:    debug
            type:     rotating_file
            path:     '%kernel.logs_dir%/scrutinizer.log'
            channels: [scrutinizer]
            max_files: 7
        loop:
            level:    debug
            type:     rotating_file
            path:     '%kernel.logs_dir%/loop.log'
            channels: [loop]
            max_files: 2