services:
    App\Unit\StatusCodeService:
        arguments:
            - '@App\Repository\Unit\StatusCodeRepository'
            - '@App\Unit\StatusCode\Scrutinizer'
        tags:
            - { name: uply.unit.service, identifier: status_code }

    App\Unit\StatusCode\Scrutinizer:
        arguments:
            - '@App\Monitor\Event\NotifyEventDispatcher'
            - '@App\Service\HttpHeader'

    App\Unit\CertificateExpireService:
        arguments:
            - '@App\Repository\Unit\CertificateExpireRepository'
            - '@App\Unit\CertificateExpire\Scrutinizer'
        tags:
            - { name: uply.unit.service, identifier: certificate_expire }

    App\Unit\CertificateExpire\Scrutinizer:
        arguments:
            - '@App\Monitor\Event\NotifyEventDispatcher'

    App\Unit\GooglePageSpeedService:
        arguments:
            - '@App\Repository\Unit\GooglePageSpeedRepository'
            - '@App\Unit\GooglePageSpeed\Scrutinizer'
        tags:
            - { name: uply.unit.service, identifier: google_page_speed }

    App\Unit\GooglePageSpeed\Scrutinizer:
        arguments:
            - '@App\Monitor\Event\NotifyEventDispatcher'
            - '@App\Service\Curl\CurlRequestFactory'
            - '%env(GOOGLE_PAGE_SPEED_KEY)%'
