# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'de'

services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false
        bind:
            $defaultDiscordWebHook: '%env(DISCORD_WEBHOOK)%'
            $defaultSlackWebHook: '%env(SLACK_WEBHOOK)%'
            $projectDir: '%kernel.project_dir%'
            $apiKey: '%env(UPLY_API_KEY)%'
            $heartbeatFile: '%kernel.project_dir%/data/heartbeat'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity}'

    App\Command\:
        resource: '../src/Command'
        tags: ['console.command']

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Command\JobProcessCommand:
        tags:
            - { name: 'console.command' }
        calls:
            - [setLogger, ['@monolog.logger']]

    App\Command\JobLoopCommand:
        tags:
            - { name: 'console.command' }
        calls:
            - [setLogger, ['@monolog.logger.loop']]

    App\Notification\Event\Listener\SendDiscordNotificationListener:
        tags:
            - { name: kernel.event_listener, event: uply.notification.send, method: onNotificationSend }

    App\Notification\Event\Listener\SendSlackNotificationListener:
        tags:
            - { name: kernel.event_listener, event: uply.notification.send, method: onNotificationSend }

    App\Repository\JobRepository:
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - App\Entity\Job

    App\Repository\Unit\StatusCodeRepository:
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - App\Entity\Unit\StatusCode

    App\Repository\Unit\CertificateExpireRepository:
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - App\Entity\Unit\CertificateExpire

    App\Repository\Unit\ContentHashRepository:
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - App\Entity\Unit\ContentHash

    App\Scrutinizer\Services\:
        resource: '../src/Scrutinizer/Services/*'
        tags:
            - { name: uply.scrutinizer }
        calls:
            - [setNotificationDataFactory, ['@App\Notification\NotificationDataFactory']]
            - [setLogger, ['@monolog.logger.scrutinizer']]
