services:
    App\Monitor\Unit\AbstractUnitCheck:
        abstract:  false
        public: true
        arguments:
            - '@App\Monitor\UnitParameterBagFactory'
            - '@event_dispatcher'

    App\Monitor\Unit\StatusCodeUnit:
        parent: App\Monitor\Unit\AbstractUnitCheck
        arguments:
            $repository: '@App\Repository\Unit\StatusCodeRepository'
            $httpHeader: '@App\Service\HttpHeader'

    App\Monitor\Unit\CertificateExpireUnit:
        parent: App\Monitor\Unit\AbstractUnitCheck
        arguments:
            $repository: '@App\Repository\Unit\CertificateExpireRepository'

    App\Monitor\Unit\GooglePageSpeedUnit:
        parent: App\Monitor\Unit\AbstractUnitCheck
        arguments:
            $repository: '@App\Repository\Unit\GooglePageSpeedRepository'
            $curlRequestFactory: '@App\Service\Curl\CurlRequestFactory'
            $apiKey: '%env(GOOGLE_PAGE_SPEED_KEY)%'
