services:
    App\Monitor\Unit\AbstractBaseUnit:
        abstract:  true
        public: false
        arguments:
            - '@App\Monitor\UnitParameterBagFactory'
            - '@event_dispatcher'

    App\Monitor\Unit\StatusCodeUnit:
        parent: App\Monitor\Unit\AbstractBaseUnit
        arguments:
            $repository: '@App\Repository\Unit\StatusCodeRepository'
            $httpHeader: '@App\Service\HttpHeader'
        tags:
            - { name: uply.monitor.unit, identifier: status_code }

    App\Monitor\Unit\CertificateExpireUnit:
        parent: App\Monitor\Unit\AbstractBaseUnit
        arguments:
            $repository: '@App\Repository\Unit\CertificateExpireRepository'
        tags:
            - { name: uply.monitor.unit, identifier: certificate_expire }

    App\Monitor\Unit\GooglePageSpeedUnit:
        parent: App\Monitor\Unit\AbstractBaseUnit
        arguments:
            $repository: '@App\Repository\Unit\GooglePageSpeedRepository'
            $curlRequest: '@App\Service\CurlRequest'
            $apiKey: '%env(GOOGLE_PAGE_SPEED_KEY)%'
        tags:
            - { name: uply.monitor.unit, identifier: google_page_speed }
